### ISSUE TITLE
Regional standard bug. 

### ISSUE THREAD

**Issue by seralekseenko** [Kovalevskyi-Academy/testing-framework#6]
Предполагаю, что ошибки связаны с региональными стандартами на конкретном "компуктере". Где-то принято разделять дробную часть точкой, а где-то запятой. По аналогии со `\n` на Линуксе и `\n\r` на Винде.

PrintStreamWrapperTest...

- testPrintDouble (313 строка):
    - Expected: 1,0
    - Actual:      1.0
- testPrintlnDouble (596 строка):
    - Expected: 1,0
    - Actual:      1.0
- testPrintFloat (285 строка):
    - Expected: 1,0
    - Actual:      1.0
- testPrintlnFloat (567 строка):
    - Expected: 1,0
    - Actual:      1.0

**Comment by EcstasyAwesome** [comment]
@seralekseenko 509df9f06518677844df6e2fbf43878ac8cc1d0a решило проблему?

**Comment by seralekseenko** [comment]
Думаю решило. Не вижу этих ошибок больше.
